server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asistente_red_idbi
    username: idbi_user
    password: idbi123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: idbi-api-gateway